### ISSUE TITLE
Setup the Auth Command

### ISSUE THREAD

**Issue by harrisonhowardax** [harrisonhoward/plex_discord_rpc#13]
## Task

We want this command to handle the following process.

1. User initiates the command `auth`
2. The app creates a pin via `plex_pin_auth.create_pin()` (client_identifier to be a mix of the host and username)
3. Using `repeatedly` poll the `plex_pin_auth.get_token()` until the auth token has been returned.
   - Ensure that it stops after the token has expired
4. If the token expires inform the user that it expired and run the command again
5. If the token is successfully returned write it to the config

## Dependencies

- `plex_pin_auth`
- `repeatedly`

**Comment by harrisonhoward** [comment]
Completed in PR #14
