### ISSUE TITLE
Finish `SECURITY.md`

### ISSUE THREAD

**Issue by harrisonhoward** [harrisonhoward/plex_discord_rpc#7]
Fill in, complete and finalise the `SECURITY.md` file that was mistakenly committed to the repository using the base template GitHub had provided.

## Outline

- The project in itself is a security risk. The Plex token itself will be stored in plain text in the `.env` file. This will likely change in future interactions where it may be base64 encoded. It's not possible to encrypt this token due to the publicity of the project as well as installing the code still making it publicly readable.
 - This means this file has to indicate that using the project you have to know what you are doing and know that the responsibility of the account being compromised is not of fault of the repository authors and contributors and you are responsible for your Plex account security.
 - The file must indicate the only the latest version of the package is the most secure. It is recommended to always be on the latest version if a new version is to be released. Keeping a tab on the version is not always ideal however if an update to security of your Plex token is dispatched then 100% update the project.
 - Provide my personal email as a method of communicating potential security vulnerabilities or indicate that publishing an issue is also welcome for not too serious vulnerabilities if any to arise.

**Comment by harrisonhowardax** [comment]
Completed in PR #10
